/*
 * Playcanvas Extras v1.28.0 revision 7952233b
 * Copyright 2011-2020 PlayCanvas Ltd. All rights reserved.
 */
;(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory();
    } else {
        root.pc = factory();
    }
}(this, function () {

Object.assign(pc,function(){var m=function(d){this._frameIndex=0;this._frameTimings=[];this._timings=[];this._prevTimings=[];d.on("frameupdate",this.begin.bind(this,"update"));d.on("framerender",this.mark.bind(this,"render"));d.on("frameend",this.mark.bind(this,"other"))};Object.assign(m.prototype,{begin:function(d){this._frameIndex<this._frameTimings.length&&this._frameTimings.splice(this._frameIndex);var h=this._prevTimings;this._prevTimings=this._timings;this._timings=this._frameTimings;this._frameTimings=
h;this._frameIndex=0;this.mark(d)},mark:function(d){var h=pc.now();if(0<this._frameIndex){var g=this._frameTimings[this._frameIndex-1];g[1]=h-g[1]}else 0<this._timings.length&&(g=this._timings[this._timings.length-1],g[1]=h-g[1]);this._frameIndex>=this._frameTimings.length?this._frameTimings.push([d,h]):(g=this._frameTimings[this._frameIndex],g[0]=d,g[1]=h);this._frameIndex++}});Object.defineProperty(m.prototype,"timings",{get:function(){return this._timings.slice(0,-1).map(function(d){return d[1]})}});
return{CpuTimer:m}}());Object.assign(pc,function(){var m=function(d){this._gl=d.graphicsDevice.gl;this._ext=d.graphicsDevice.extDisjointTimerQuery;this._freeQueries=[];this._frameQueries=[];this._frames=[];this._timings=[];this._prevTimings=[];d.on("frameupdate",this.begin.bind(this,"update"));d.on("framerender",this.mark.bind(this,"render"));d.on("frameend",this.end.bind(this))};Object.assign(m.prototype,{begin:function(d){0<this._frameQueries.length&&this.end();this._checkDisjoint();if(0<this._frames.length&&this._resolveFrameTimings(this._frames[0],
this._prevTimings)){var h=this._prevTimings;this._prevTimings=this._timings;this._timings=h;this._freeQueries=this._freeQueries.concat(this._frames.splice(0,1)[0])}this.mark(d)},mark:function(d){0<this._frameQueries.length&&this._gl.endQuery(this._ext.TIME_ELAPSED_EXT);var h=this._allocateQuery();h[0]=d;this._gl.beginQuery(this._ext.TIME_ELAPSED_EXT,h[1]);this._frameQueries.push(h)},end:function(){this._gl.endQuery(this._ext.TIME_ELAPSED_EXT);this._frames.push(this._frameQueries);this._frameQueries=
[]},_checkDisjoint:function(){this._gl.getParameter(this._ext.GPU_DISJOINT_EXT)&&(this._freeQueries=[this._frames,[this._frameQueries],[this._freeQueries]].flat(2),this._frameQueries=[],this._frames=[])},_allocateQuery:function(){return 0<this._freeQueries.length?this._freeQueries.splice(-1,1)[0]:["",this._gl.createQuery()]},_resolveFrameTimings:function(d,h){if(!this._gl.getQueryParameter(d[d.length-1][1],this._gl.QUERY_RESULT_AVAILABLE))return!1;for(var g=0;g<d.length;++g)h[g]=[d[g][0],1E-6*this._gl.getQueryParameter(d[g][1],
this._gl.QUERY_RESULT)];return!0}});Object.defineProperty(m.prototype,"timings",{get:function(){return this._timings.map(function(d){return d[1]})}});return{GpuTimer:m}}());Object.assign(pc,function(){var m=function(b,a){a=a||128;for(var c=new pc.VertexFormat(b,[{semantic:pc.SEMANTIC_POSITION,components:2,type:pc.TYPE_FLOAT32},{semantic:pc.SEMANTIC_TEXCOORD0,components:4,type:pc.TYPE_FLOAT32}]),f=new Uint32Array(6*a),e=0;e<a;++e)f[6*e]=4*e,f[6*e+1]=4*e+1,f[6*e+2]=4*e+2,f[6*e+3]=4*e,f[6*e+4]=4*e+2,f[6*e+5]=4*e+3;this.device=b;this.shader=pc.shaderChunks.createShaderFromCode(b,"attribute vec2 vertex_position;\nattribute vec4 vertex_texCoord0;\nuniform vec4 screenAndTextureSize;\nvarying vec4 uv0;\nvoid main(void) {\n    vec2 pos = vertex_position.xy / screenAndTextureSize.xy;\n    gl_Position = vec4(pos * 2.0 - 1.0, 0.5, 1.0);\n    uv0 = vec4(vertex_texCoord0.xy / screenAndTextureSize.zw, vertex_texCoord0.zw);\n}\n",
"varying vec4 uv0;\nuniform vec4 clr;\nuniform sampler2D source;\nvoid main (void) {\n    vec4 tex = texture2D(source, uv0.xy);\n    if (tex.rgb != vec3(1, 1, 1)) {\n       if (uv0.w < tex.r)\n           tex = vec4(1.0, 0.3, 0.3, 1.0);\n       else if (uv0.w < tex.g)\n           tex = vec4(0.3, 1.0, 0.3, 1.0);\n       else\n           tex = vec4(0.0, 0.0, 0.0, 1.0);\n    }\n    gl_FragColor = tex * clr;\n}\n","mini-stats");this.buffer=new pc.VertexBuffer(b,c,4*a,pc.BUFFER_STREAM);this.data=new Float32Array(this.buffer.numBytes/
4);this.indexBuffer=new pc.IndexBuffer(b,pc.INDEXFORMAT_UINT32,6*a,pc.BUFFER_STATIC,f);this.prims=[];this.prim=null;this.primIndex=-1;this.quads=0;this.clrId=b.scope.resolve("clr");this.clr=new Float32Array(4);this.screenTextureSizeId=b.scope.resolve("screenAndTextureSize");this.screenTextureSize=new Float32Array(4)};Object.assign(m.prototype,{quad:function(b,a,c,f,e,d,q,k,l){var p=this.quads++,n=this.prim;n&&n.texture===b?n.count+=6:(this.primIndex++,this.primIndex===this.prims.length?(n={type:pc.PRIMITIVE_TRIANGLES,
indexed:!0,base:6*p,count:6,texture:b},this.prims.push(n)):(n=this.prims[this.primIndex],n.base=6*p,n.count=6,n.texture=b),this.prim=n);b=a+f;n=c+e;f=d+(void 0===k?f:k);e=q+(void 0===l?e:l);this.data.set([a,c,d,q,0,0,b,c,f,q,1,0,b,n,f,e,1,1,a,n,d,e,0,1],24*p)},render:function(b){var a=this.device,c=this.buffer;c.setData(this.data.buffer);a.updateBegin();a.setDepthTest(!1);a.setDepthWrite(!1);a.setCullMode(pc.CULLFACE_NONE);a.setBlending(!0);a.setBlendFunctionSeparate(pc.BLENDMODE_SRC_ALPHA,pc.BLENDMODE_ONE_MINUS_SRC_ALPHA,
pc.BLENDMODE_ONE,pc.BLENDMODE_ONE);a.setBlendEquationSeparate(pc.BLENDEQUATION_ADD,pc.BLENDEQUATION_ADD);a.setVertexBuffer(c,0);a.setIndexBuffer(this.indexBuffer);a.setShader(this.shader);c=Math.min(a.maxPixelRatio,window.devicePixelRatio);this.clr.set(b,0);this.clrId.setValue(this.clr);this.screenTextureSize[0]=a.width/c;this.screenTextureSize[1]=a.height/c;for(b=0;b<=this.primIndex;++b)c=this.prims[b],this.screenTextureSize[2]=c.texture.width,this.screenTextureSize[3]=c.texture.height,this.screenTextureSizeId.setValue(this.screenTextureSize),
a.constantTexSource.setValue(c.texture),a.draw(c);a.updateEnd();this.prim=null;this.primIndex=-1;this.quads=0}});var d=function(b,a){var c=document.createElement("canvas");c.width=b.width;c.height=b.height;var f=c.getContext("2d",{alpha:!0});f.font='10px "Lucida Console", Monaco, monospace';f.textAlign="left";f.textBaseline="alphabetic";f.fillStyle="rgb(255, 255, 255)";var e=5,d=5,q=[],k;for(k=0;k<a.length;++k){var l=f.measureText(a[k]),h=Math.ceil(-l.actualBoundingBoxLeft),n=Math.ceil(l.actualBoundingBoxRight),
g=Math.ceil(l.actualBoundingBoxAscent);l=Math.ceil(l.actualBoundingBoxDescent);var m=h+n,r=g+l;e+m>=c.width&&(e=5,d+=16);f.fillText(a[k],e-h,d+g);q.push({l:h,r:n,a:g,d:l,x:e,y:d,w:m,h:r});e+=m+5}var t={};a.forEach(function(a,b){t[a]=b});this.words=a;this.wordMap=t;this.placements=q;this.texture=b;a=f.getImageData(0,0,c.width,c.height);c=b.lock();for(d=0;d<a.height;++d)for(e=0;e<a.width;++e)f=4*(e+d*b.width),c[f]=255,c[f+1]=255,c[f+2]=255,c[f+3]=a.data[4*(e+(a.height-1-d)*a.width)+3]};Object.assign(d.prototype,
{render:function(b,a,c,d){return(a=this.placements[this.wordMap[a]])?(b.quad(this.texture,c+a.l-1,d-a.d+1,a.w+2,a.h+2,a.x-1,64-a.y-a.h-1),a.w):0}});var h=function(b,a,c,d,e){this.name=b;this.device=a.graphicsDevice;this.timer=c;this.enabled=!1;this.avgCount=this.avgTimer=this.avgTotal=0;this.timingText="";this.texture=d;this.yOffset=e;this.cursor=0;this.sample=new Uint8Array(4);this.sample.set([0,0,0,255]);a.on("frameupdate",this.update.bind(this));this.counter=0};Object.assign(h.prototype,{update:function(b){var a=
this.timer.timings,c=a.reduce(function(a,b){return a+b},0);this.avgTotal+=c;this.avgTimer+=b;this.avgCount++;1E3<this.avgTimer&&(this.timingText=(this.avgTotal/this.avgCount).toFixed(1),this.avgCount=this.avgTotal=this.avgTimer=0);if(this.enabled){for(c=b=0;c<a.length;++c)b=Math.min(255,b+Math.floor(5.3125*a[c])),this.sample[c]=b;a=this.device.gl;this.device.bindTexture(this.texture);a.texSubImage2D(a.TEXTURE_2D,0,this.cursor,this.yOffset,1,1,a.RGBA,a.UNSIGNED_BYTE,this.sample);this.cursor++;this.cursor===
this.texture.width&&(this.cursor=0)}},render:function(b,a,c,d,e){b.quad(this.texture,a+d,c,-d,e,this.cursor,.5+(this.enabled?this.yOffset:0),-d,0)}});var g=function(b){this.ms=0;var a=this;b.on("frameupdate",function(b){a.ms=b})};Object.defineProperty(g.prototype,"timings",{get:function(){return[this.ms]}});var r=function(b){for(var a=b.graphicsDevice,c=new pc.Texture(a,{name:"mini-stats",width:256,height:32,mipmaps:!1,minFilter:pc.FILTER_NEAREST,magFilter:pc.FILTER_NEAREST}),f=new d(c,"Frame CPU GPU ms 0 1 2 3 4 5 6 7 8 9 .".split(" ")),
e=c.lock(),p=0;p<4*c.width;++p)e.set([0,0,0,255],4*p);c.unlock();e=[new h("Frame",b,new g(b),c,1),new h("CPU",b,new pc.CpuTimer(b),c,2)];a.extDisjointTimerQuery&&e.push(new h("GPU",b,new pc.GpuTimer(b),c,3));var q=[{width:100,height:16,graphs:!1},{width:128,height:32,graphs:!0},{width:256,height:64,graphs:!0}],k=0,l=this;p=document.createElement("div");p.style.cssText="position:fixed;bottom:0;left:0;background:transparent;";document.body.appendChild(p);p.addEventListener("mouseenter",function(a){l.opacity=
1});p.addEventListener("mouseleave",function(a){l.opacity=.5});p.addEventListener("click",function(a){a.preventDefault();l.enabled&&(k=(k+1)%q.length,l.resize(q[k].width,q[k].height,q[k].graphs))});a.on("resizecanvas",function(){l.updateDiv()});b.on("postrender",function(){l.enabled&&l.render()});this.device=a;this.texture=c;this.wordAtlas=f;this.render2d=new m(a);this.graphs=e;this.div=p;this.height=this.width=0;this.gspacing=2;this.clr=[1,1,1,.5];this.enabled=!0;this.resize(q[k].width,q[k].height,
q[k].graphs)};Object.defineProperties(r.prototype,{opacity:{get:function(){return this.clr[3]},set:function(b){this.clr[3]=b}},overallHeight:{get:function(){var b=this.graphs;return this.height*b.length+this.gspacing*(b.length-1)}}});Object.assign(r.prototype,{render:function(){var b=this.graphs,a=this.wordAtlas,c=this.render2d,d=this.width,e=this.height,h=this.gspacing,g;for(g=0;g<b.length;++g){var k=b[g];var l=g*(e+h);k.render(c,0,l,d,e);var m=1;l+=e-13;m+=a.render(c,k.name,m,l)+10;var n=k.timingText;
for(k=0;k<n.length;++k)m+=a.render(c,n[k],m,l);a.render(c,"ms",m,l)}c.render(this.clr)},resize:function(b,a,c){for(var d=this.graphs,e=0;e<d.length;++e)d[e].enabled=c;this.width=b;this.height=a;this.updateDiv()},updateDiv:function(){var b=this.device.canvas.getBoundingClientRect();this.div.style.left=b.left+"px";this.div.style.bottom=window.innerHeight-b.bottom+"px";this.div.style.width=this.width+"px";this.div.style.height=this.overallHeight+"px"}});return{MiniStats:r}}());

return pc;
}));

